# Site Settings
locale           : "fr-FR"
title            : "Le décodeur, by Nicolas Jouanno"
sitetitle        : "Le Décodeur"
headline         : "Le rendez-vous hebdomadaire pour partager des retours d'expérience inspirants et motivants."
description      : "Product Manager / Sportsman / Blogger."
siteurl          : https://blog.nicolasjouanno.com
meta_description : "I believes that the best marketing comes from the product. He dissects and decrypts everyday, business, design and tech resources, to keep an overview. - Nicolas Jouanno"
meta_keywords    : "product management, digital product, startup, freelance, indie hacker, solopreneur, nicolas jouanno, tech, business, marketing, marketer, web-developper, designer"
logo             : 'assets/public/images/brand/logo.png'
comments:
  disqus: 
    shortname    : 'nicolasjouanno-com'  
reCaptcha:
  siteKey        :
  secret         :

# Post settings
imgpost   : assets/public/images/posts

# SEO Related
google_verification :
bing_verification   :
yandex_verification :
naver_verification  :

# Analytics
google_analytics: 'UA-33078029-1'

# Social sharing
og_image: "assets/public/images/jumbotron.jpg" # Open Graph/Twitter default site image
twitter:
  username  : "@nicolasjouanno"
facebook:
  username  : 10210003510697734
  app_id    : #502710249769535
  publishe  : #https://www.facebook.com/app.vtt.bzh
social:
  type  : # Person or Organization (defaults to Person)
  name  : # If the user or organization name differs from the site's name
  links : # An array of links to social media profiles

# Outputting
permalink : /:title:output_ext
# paginate: 9
# paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  # - jekyll-archives  
  # - jekyll-minifier

whitelist:
  - jekyll-paginate
    
# Archives
# jekyll-archives:
#   enabled:
#    - categories
#  layout: archive
#  permalinks:
#    category: '/:name/'
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/



# Minification
# jekyll-minifier:
#   exclude: 'feed.xml'
    
# Other
markdown: kramdown
highlighter: rouge
future: false
