# Site Settings
locale           : "fr-FR"
title            : "Nicolas Jouanno"
headline         : "Créateur digital pour les sportifs & outdoor enthusiast."
siteurl          : "https://nicolasjouanno.com"
url              : "https://nicolasjouanno.com"
logo             : 'assets/public/images/brand/logo.png'
comments:
  disqus: 
    shortname    : 'nicolasjouanno-com'  
reCaptcha:
  siteKey        :
  secret         :
default_date: "01-01-2013"

# Post settings
imgpost   : assets/public/images/posts

# SEO Related
meta_description : "Moi c'est Nicolas Jouanno, sportif et créateur digital. Avec vous, je partage chaque défi et développe de nouveaux projets."
meta_keywords    : 
  - "product management"
  - "product manager freelance"
  - "chef de projet web freelance"
  - "chef de projet digital freelance"
  - "digital product"
  - "startup"
  - "freelance"
  - "indie hacker"
  - "solopreneur"
  - "nicolas jouanno"
  - "tech"
  - "business"
  - "marketing"
  - "marketer"
  - "web-developper"
  - "designer"
google_verification :
bing_verification   :
yandex_verification :
naver_verification  :

# Post settings
imgpost   : assets/public/images/posts
subscriber_number : "3 500"
ads_booking_link: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSTrV8CdtVRmUyoENBgfA3kv_PpQeSXvvzh71M-QoY5vIslAU9EzmdRbyxShSkpyAqlmV_QC6_YJU43/pubhtml?gid=0&single=true"

# Analytics
google_analytics: 'UA-33078029-1'

# Social sharing
og_image: "assets/public/images/jumbotron.jpg" # Open Graph/Twitter default site image
twitter:
  username  : "@nicolasjouanno"
  publisher : "https://twitter.com/NicolasJouanno"
facebook:
  profil_url  : "https://www.facebook.com/njouanno"
  app_id    : 870898643116106
  publisher  : "https://www.facebook.com/blog.nicolasjouanno/"
instagram :
  publisher : "http://instagram.com/nicolasjouanno/"
google_plus : 
  publisher : "https://plus.google.com/u/0/101743465600034380035"
mediumcom   : 
  publisher : "https://medium.com/@nicolasjouanno"
linkedin: 
  publisher : "https://fr.linkedin.com/in/nicolasjouanno"
viadeo: 
  publisher : "https://fr.viadeo.com/fr/profile/nicolas.jouanno"
pinterest: 
  publisher : "https://www.pinterest.fr/nicolasjouanno/"
social:
  type  : # Person or Organization (defaults to Person)
  name  : # If the user or organization name differs from the site's name
  links : # An array of links to social media profiles

# address
address :
  street : "rue du resteu vihan"
  code : "56300"
  coutry : "FR"
  city: "Pontivy, France"

devis_link: "/devis.html"

# Outputting
permalink : /:title:output_ext
paginate: 24
paginate_path: /stories/latest/page:num/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  # - jekyll-archives  
  # - jekyll-minifier

whitelist:
  - jekyll-paginate
    
# Archives
# jekyll-archives:
#   enabled:
#    - categories
#  layout: archive
#  permalinks:
#    category: '/:name/'
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Minification
# jekyll-minifier:
#   exclude: 'feed.xml'
    
# Other
markdown: kramdown
highlighter: rouge
future: false
