- name: "MVP"
  url: "#"
  img: "fas fa-chart-line"
  features: 
    - name: "Design thinking"
    - name: "User flow"
    - name: "Wireframe & Prototyping"
    - name: "KPI tracking"
    - name: "Product Roadmap"
    - name: "Landing page"
- name: "Développement Web"
  url: "#"
  img: "fas fa-pencil-alt"
  features: 
    - name: "Front-end: HTML5 - CSS3 - JS"
    - name: "Back-end: NodeJS - PHP - Python - Ruby"
    - name: "Database: MongoDB - MySQL - PostgreSQL"
    - name: "Framework: ExpressJS - Django - Flask - VueJS"
    - name: "Unit Test - Git - Github"
    - name: "POO - MVC"
- name: "Automatisation"
  url: "#"
  img: "fas fa-code"
  features: 
    - name: "API"
    - name: "Growth Engineering"
    - name: "Scrapping"
    - name: "Data Analyse"
    - name: "Script"
